export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND",
  RESULT_NOT_FOUND: "RESULT_NOT_FOUND",
  RESULT_NOT_ABNORMAL: "RESULT_NOT_ABNORMAL",
  OWNER_NOT_FOUND: "OWNER_NOT_FOUND",
  HAZARD_TICKET_NOT_FOUND: "HAZARD_TICKET_NOT_FOUND",
  HAZARD_TICKET_DUPLICATE_OPEN: "HAZARD_TICKET_DUPLICATE_OPEN",
  HAZARD_TICKET_BAD_STATE: "HAZARD_TICKET_BAD_STATE"
} as const;
