ERROR_CODES = {
    "AUTH_REQUIRED": "AUTH_REQUIRED",
    "RBAC_DENIED": "RBAC_DENIED",
    "VALIDATION_FAILED": "VALIDATION_FAILED",
    "HAZARD_ALREADY_OPEN": "HAZARD_ALREADY_OPEN",
    "HAZARD_NOT_FOUND": "HAZARD_NOT_FOUND",
    "INVALID_HAZARD_TRANSITION": "INVALID_HAZARD_TRANSITION",
    "RESULT_NOT_FOUND": "RESULT_NOT_FOUND"
}
